### ISSUE TITLE
Issue with `in` values

### ISSUE THREAD

**Issue by akoppela** [elm-community/typed-svg#31]
`in` values should start from a capital letter.

**Comment by akoppela** [comment]
[PR](https://github.com/elm-community/typed-svg/pull/30)

**Comment by rupertlssmith** [comment]
Good spot. I've merge the pull request in, its a non API breaking change so I will publish a new minor version - real soon!

**Comment by rupertlssmith** [comment]
That has been released as 5.0.1.
