### ISSUE TITLE
Add documentation for the Text section of `TypedSvg`

### ISSUE THREAD

**Issue by AlienKevin** [elm-community/typed-svg#42]
I initially had trouble implementing a text node. Following the pattern of other functions like `circle` and `rect`, I thought that the text content for `text_` needs to be defined as an `Attribute`. However, no such `Attribute` exists. It took me a long time to figure out that `text` actually resides in `TypedSvg.Core` and that the `text_` is for creating a `<text>` element. To help clear up this confusion, **can we provide a brief explanation and an example code in the Text section of `TypedSvg`**?

**Comment by rupertlssmith** [comment]
Yes, it probably does need better explanation.

If you submit a PR with some improved docs it will get merged in.

**Comment by AlienKevin** [comment]
@rupertlssmith Made a PR.

**Comment by rupertlssmith** [comment]
PR merged.
