### ISSUE TITLE
Put a deprecation notice on xlinkHref and add the new href attribute

### ISSUE THREAD

**Issue by AlienKevin** [elm-community/typed-svg#45]
In most cases, `xlinkHref` is still supported by most browsers but usage in elements like `image` is not longer supported (tested on latest chrome. and safari). Considering that new `href` attribute is widely used in [many elements](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/href) and the transition has [relatively matured](https://caniuse.com/?search=href), I feel it's time to put a deprecation notice on `xlinkHref` and add `href` to our API.

**Comment by rupertlssmith** [comment]
Yes, good idea. And reference `href` from the `xlinkHref` docs as the better way to do it.

**Comment by AlienKevin** [comment]
Made a PR
