### ISSUE TITLE
fontFamily and fontSize don't get correct attribute names

### ISSUE THREAD

**Issue by rupertlssmith** [elm-community/typed-svg#5]
The attribute names in the SVG should be:

font-family
font-size

These are the only ones I tried, probably plenty more that need converting from camelCase to kebab-case.

**Comment by canadaduane** [comment]
Yeah, the weird thing (to me) about the svg spec is that some are kebab and others are camelCase. My understanding is kebab-case is for attributes that can be affected by CSS, while camelCase attributes cannot. Anyway, thanks for the catch.
