### ISSUE TITLE
`TypedSvg.Attributes.version` takes a `Float`

### ISSUE THREAD

**Issue by zakvdm** [elm-community/typed-svg#8]
Probably not a big deal, but seems like this should either be `String` or a new type.

**Comment by rupertlssmith** [comment]
May be best as a String.

**Comment by rupertlssmith** [comment]
Going with a String instead of introducing a new type. There are two official values this can take "1.0" and "1.1". However there are some variations that some browsers may accept and it seems nicer to allow the user to put anything in here to allow for experimentation.

**Comment by nukisman** [comment]
@rupertlssmith @zakvdm 
I suppose this typed version would be better:
```elm
type Version 
    = Version_1_0
    | Version_1_1
    | Custom String
```
